#include "runtime/peraviz_visual_runtime_godot.h"

namespace godot {

// Registers the visual runtime methods for GDScript callers.
void PeravizVisualRuntime::_bind_methods() {
    ClassDB::bind_method(D_METHOD("clear"), &PeravizVisualRuntime::clear);
    ClassDB::bind_method(D_METHOD("install_compiled_scene", "packed_scene"), &PeravizVisualRuntime::install_compiled_scene);
    ClassDB::bind_method(D_METHOD("submit_universe_frame", "universe_id", "data"), &PeravizVisualRuntime::submit_universe_frame);
    ClassDB::bind_method(D_METHOD("consume_latest_visual_frame"), &PeravizVisualRuntime::consume_latest_visual_frame);
    ClassDB::bind_method(D_METHOD("get_visual_frame_schema"), &PeravizVisualRuntime::get_visual_frame_schema);
    ClassDB::bind_method(D_METHOD("get_stats"), &PeravizVisualRuntime::get_stats);
}

// Clears all native fixture bindings, render parameters, pending frames, and stats.
void PeravizVisualRuntime::clear() {
    core_.clear();
}

// Installs a variable-length compiled scene payload generated by native parser-owned code.
void PeravizVisualRuntime::install_compiled_scene(const Dictionary &packed_scene) {
    peraviz::runtime::CompiledRuntimeScene scene;
    PackedInt32Array integers = packed_scene.get("integers", PackedInt32Array());
    PackedFloat32Array floats = packed_scene.get("floats", PackedFloat32Array());
    if (integers.size() < 6 || integers[0] < 1 || integers[0] > 2) {
        core_.install_compiled_scene(scene);
        return;
    }
    int64_t cursor = 1;
    const int fixture_count = integers[cursor++];
    const int program_count = integers[cursor++];
    const int property_count = integers[cursor++];
    const int color_target_count = integers[cursor++];
    int wheel_palette_count = 0;
    int wheel_binding_count = 0;
    if (integers[0] >= 2 && integers.size() >= 8) {
        wheel_palette_count = integers[cursor++];
        wheel_binding_count = integers[cursor++];
    }
    cursor++;
    for (int index = 0; index < fixture_count && cursor + 6 <= integers.size(); ++index) {
        peraviz::runtime::CompiledFixtureInstance fixture;
        fixture.fixture_id = integers[cursor++];
        fixture.universe_id = integers[cursor++];
        fixture.start_address = integers[cursor++];
        cursor++;
        const int luminous_index = integers[cursor++];
        const int beam_index = integers[cursor++];
        fixture.luminous_flux = luminous_index >= 0 && luminous_index < floats.size() ? floats[luminous_index] : fixture.luminous_flux;
        fixture.beam_angle_default = beam_index >= 0 && beam_index < floats.size() ? floats[beam_index] : fixture.beam_angle_default;
        scene.fixtures.push_back(fixture);
    }
    for (int index = 0; index < program_count && cursor + 8 <= integers.size(); ++index) {
        peraviz::runtime::CompiledDmxSourceProgram program;
        program.program_id = integers[cursor++];
        program.semantic = static_cast<peraviz::runtime::CompiledSemantic>(integers[cursor++]);
        const int source_count = integers[cursor++];
        program.dmx_from = static_cast<uint32_t>(integers[cursor++]);
        program.dmx_to = static_cast<uint32_t>(integers[cursor++]);
        const int physical_from_index = integers[cursor++];
        const int physical_to_index = integers[cursor++];
        cursor++;
        program.physical_from = physical_from_index >= 0 && physical_from_index < floats.size() ? floats[physical_from_index] : 0.0;
        program.physical_to = physical_to_index >= 0 && physical_to_index < floats.size() ? floats[physical_to_index] : 1.0;
        for (int source_index = 0; source_index < source_count && cursor + 3 <= integers.size(); ++source_index) {
            peraviz::runtime::CompiledDmxByteSource source;
            source.universe_id = integers[cursor++];
            source.address = integers[cursor++];
            source.byte_order = integers[cursor++];
            program.sources.push_back(source);
        }
        scene.source_programs.push_back(program);
    }
    for (int index = 0; index < property_count && cursor + 6 <= integers.size(); ++index) {
        peraviz::runtime::CompiledComponentProperty property;
        property.property_id = integers[cursor++];
        property.fixture_id = integers[cursor++];
        property.component_id = integers[cursor++];
        property.render_target_id = integers[cursor++];
        property.semantic = static_cast<peraviz::runtime::CompiledSemantic>(integers[cursor++]);
        const int contributor_count = integers[cursor++];
        for (int contributor_index = 0; contributor_index < contributor_count && cursor + 3 <= integers.size(); ++contributor_index) {
            peraviz::runtime::CompiledPropertyContributor contributor;
            contributor.source_program_id = integers[cursor++];
            const int weight_index = integers[cursor++];
            contributor.operation = static_cast<peraviz::runtime::CompiledContributorOperation>(integers[cursor++]);
            contributor.weight = weight_index >= 0 && weight_index < floats.size() ? floats[weight_index] : 1.0;
            property.contributors.push_back(contributor);
        }
        scene.properties.push_back(property);
    }
    for (int index = 0; index < color_target_count && cursor + 6 <= integers.size(); ++index) {
        peraviz::runtime::CompiledColorTargetProgram target;
        target.color_target_id = integers[cursor++];
        target.fixture_id = integers[cursor++];
        target.beam_render_target_id = integers[cursor++];
        target.geometry_id = integers[cursor++];
        target.additive_source = integers[cursor++] != 0;
        const int input_count = integers[cursor++];
        for (int input_index = 0; input_index < input_count && cursor + 4 <= integers.size(); ++input_index) {
            peraviz::runtime::CompiledColorInputBinding input;
            input.source_program_id = integers[cursor++];
            input.semantic = static_cast<peraviz::runtime::CompiledSemantic>(integers[cursor++]);
            const int default_value_index = integers[cursor++];
            input.default_value = default_value_index >= 0 && default_value_index < floats.size() ? floats[default_value_index] : 0.0;
            input.use_normalized_value = integers[cursor++] != 0;
            target.inputs.push_back(input);
        }
        scene.color_targets.push_back(target);
    }

    for (int index = 0; index < wheel_palette_count && cursor + 4 <= integers.size(); ++index) {
        peraviz::runtime::CompiledWheelPalette palette;
        palette.wheel_renderer_id = integers[cursor++];
        palette.fixture_id = integers[cursor++];
        const int placement_index = integers[cursor++];
        palette.placement_offset_degrees = placement_index >= 0 && placement_index < floats.size() ? floats[placement_index] : palette.placement_offset_degrees;
        const int slot_count = integers[cursor++];
        for (int slot_index = 0; slot_index < slot_count && cursor + 9 <= integers.size(); ++slot_index) {
            peraviz::runtime::CompiledWheelPaletteSlot slot;
            slot.slot_index = integers[cursor++];
            const int sr = integers[cursor++];
            const int sg = integers[cursor++];
            const int sb = integers[cursor++];
            const int lr = integers[cursor++];
            const int lg = integers[cursor++];
            const int lb = integers[cursor++];
            const int gain = integers[cursor++];
            slot.srgb_red = sr >= 0 && sr < floats.size() ? floats[sr] : slot.srgb_red;
            slot.srgb_green = sg >= 0 && sg < floats.size() ? floats[sg] : slot.srgb_green;
            slot.srgb_blue = sb >= 0 && sb < floats.size() ? floats[sb] : slot.srgb_blue;
            slot.linear_red = lr >= 0 && lr < floats.size() ? floats[lr] : slot.linear_red;
            slot.linear_green = lg >= 0 && lg < floats.size() ? floats[lg] : slot.linear_green;
            slot.linear_blue = lb >= 0 && lb < floats.size() ? floats[lb] : slot.linear_blue;
            slot.gain = gain >= 0 && gain < floats.size() ? floats[gain] : slot.gain;
            slot.identity = integers[cursor++] != 0;
            palette.slots.push_back(slot);
        }
        scene.wheel_palettes.push_back(palette);
    }
    for (int index = 0; index < wheel_binding_count && cursor + 9 <= integers.size(); ++index) {
        peraviz::runtime::CompiledWheelTargetBinding binding;
        binding.binding_id = integers[cursor++];
        binding.fixture_id = integers[cursor++];
        binding.beam_render_target_id = integers[cursor++];
        binding.wheel_renderer_id = integers[cursor++];
        binding.source_program_id = integers[cursor++];
        binding.mode = static_cast<peraviz::runtime::CompiledWheelMode>(integers[cursor++]);
        binding.snap = integers[cursor++] != 0;
        const int placement_index = integers[cursor++];
        binding.placement_offset_degrees = placement_index >= 0 && placement_index < floats.size() ? floats[placement_index] : binding.placement_offset_degrees;
        const int set_count = integers[cursor++];
        for (int set_index = 0; set_index < set_count && cursor + 3 <= integers.size(); ++set_index) {
            peraviz::runtime::CompiledWheelChannelSet set;
            set.dmx_from = static_cast<uint32_t>(integers[cursor++]);
            set.dmx_to = static_cast<uint32_t>(integers[cursor++]);
            set.wheel_slot_index = integers[cursor++];
            binding.channel_sets.push_back(set);
        }
        scene.wheel_bindings.push_back(binding);
    }
    core_.install_compiled_scene(scene);
}

// Submits the latest snapshot for a DMX universe.
void PeravizVisualRuntime::submit_universe_frame(int universe_id, const PackedByteArray &data) {
    core_.submit_universe_frame(universe_id, data.ptr(), data.size());
}

// Consumes the latest cooked dirty visual frame as one coherent typed snapshot.
Dictionary PeravizVisualRuntime::consume_latest_visual_frame() {
    const peraviz::runtime::SectionedVisualFrame frame = core_.consume_latest_visual_frame();
    PackedInt32Array descriptors;
    descriptors.resize(static_cast<int64_t>(frame.descriptors.size()));
    for (int64_t index = 0; index < descriptors.size(); ++index) {
        descriptors.set(index, frame.descriptors[static_cast<size_t>(index)]);
    }
    PackedInt32Array integers;
    integers.resize(static_cast<int64_t>(frame.integers.size()));
    for (int64_t index = 0; index < integers.size(); ++index) {
        integers.set(index, frame.integers[static_cast<size_t>(index)]);
    }
    PackedFloat32Array floats;
    floats.resize(static_cast<int64_t>(frame.floats.size()));
    for (int64_t index = 0; index < floats.size(); ++index) {
        floats.set(index, frame.floats[static_cast<size_t>(index)]);
    }
    Dictionary out;
    out["protocol_major"] = frame.protocol_major;
    out["protocol_minor"] = frame.protocol_minor;
    out["schema_generation"] = frame.schema_generation;
    out["descriptors"] = descriptors;
    out["integers"] = integers;
    out["floats"] = floats;
    return out;
}

// Returns the installed section schema for structural registration and validation in Godot.
Dictionary PeravizVisualRuntime::get_visual_frame_schema() const {
    const peraviz::runtime::VisualFrameSchema &schema = core_.schema();
    Array sections;
    for (const peraviz::runtime::VisualSectionSchema &section : schema.sections) {
        Dictionary row;
        row["section_type"] = section.section_type;
        row["row_stride_ints"] = section.row_stride_ints;
        row["row_stride_floats"] = section.row_stride_floats;
        row["flags"] = section.flags;
        sections.push_back(row);
    }
    Dictionary out;
    out["protocol_major"] = schema.protocol_major;
    out["protocol_minor"] = schema.protocol_minor;
    out["schema_generation"] = schema.schema_generation;
    out["sections"] = sections;
    return out;
}

// Returns cumulative native runtime counters for diagnostics.
Dictionary PeravizVisualRuntime::get_stats() const {
    return stats_to_dictionary(core_.stats());
}

// Converts native visual frame stats into a Godot dictionary.
Dictionary PeravizVisualRuntime::stats_to_dictionary(const peraviz::runtime::VisualFrameStats &stats) {
    Dictionary out;
    out["packets_submitted"] = static_cast<int64_t>(stats.packets_submitted);
    out["packets_coalesced"] = static_cast<int64_t>(stats.packets_coalesced);
    out["universes_ignored"] = static_cast<int64_t>(stats.universes_ignored);
    out["universes_considered"] = static_cast<int64_t>(stats.universes_considered);
    out["fixtures_dirty"] = static_cast<int64_t>(stats.fixtures_dirty);
    out["fixtures_skipped"] = static_cast<int64_t>(stats.fixtures_skipped);
    out["changed_transform"] = static_cast<int64_t>(stats.changed_transform);
    out["changed_dimmer"] = static_cast<int64_t>(stats.changed_dimmer);
    out["changed_color"] = static_cast<int64_t>(stats.changed_color);
    out["changed_zoom"] = static_cast<int64_t>(stats.changed_zoom);
    out["color_rows"] = static_cast<int64_t>(stats.color_rows);
    out["color_targets_dirty"] = static_cast<int64_t>(stats.color_targets_dirty);
    out["color_inputs_evaluated"] = static_cast<int64_t>(stats.color_inputs_evaluated);
    out["color_targets_cooked"] = static_cast<int64_t>(stats.color_targets_cooked);
    out["changed_gobo"] = static_cast<int64_t>(stats.changed_gobo);
    out["changed_gobo_rotation"] = static_cast<int64_t>(stats.changed_gobo_rotation);
    out["gobo_topology_updates"] = static_cast<int64_t>(stats.gobo_topology_updates);
    out["gobo_parametric_updates"] = static_cast<int64_t>(stats.gobo_parametric_updates);
    out["wheel_inputs_evaluated"] = static_cast<int64_t>(stats.wheel_inputs_evaluated);
    out["wheel_targets_dirty"] = static_cast<int64_t>(stats.wheel_targets_dirty);
    out["wheel_selection_rows"] = static_cast<int64_t>(stats.wheel_selection_rows);
    return out;
}

} // namespace godot
