#include "runtime/peraviz_visual_runtime_godot.h"
#include "runtime/compiled_runtime_scene_codec.h"

namespace godot {

// Registers the visual runtime methods for GDScript callers.
void PeravizVisualRuntime::_bind_methods() {
    ClassDB::bind_method(D_METHOD("clear"), &PeravizVisualRuntime::clear);
    ClassDB::bind_method(D_METHOD("install_compiled_scene", "packed_scene"), &PeravizVisualRuntime::install_compiled_scene);
    ClassDB::bind_method(D_METHOD("submit_universe_frame", "universe_id", "data"), &PeravizVisualRuntime::submit_universe_frame);
    ClassDB::bind_method(D_METHOD("consume_latest_visual_frame"), &PeravizVisualRuntime::consume_latest_visual_frame);
    ClassDB::bind_method(D_METHOD("get_visual_frame_schema"), &PeravizVisualRuntime::get_visual_frame_schema);
    ClassDB::bind_method(D_METHOD("get_stats"), &PeravizVisualRuntime::get_stats);
}

// Clears all native fixture bindings, render parameters, pending frames, and stats.
void PeravizVisualRuntime::clear() {
    core_.clear();
}

// Installs a variable-length compiled scene payload generated by native parser-owned code.
void PeravizVisualRuntime::install_compiled_scene(const Dictionary &packed_scene) {
    const PackedInt32Array packed_integers = packed_scene.get("integers", PackedInt32Array());
    const PackedFloat32Array packed_floats = packed_scene.get("floats", PackedFloat32Array());
    std::vector<int32_t> integers(static_cast<size_t>(packed_integers.size()));
    std::vector<float> floats(static_cast<size_t>(packed_floats.size()));
    for (int64_t index = 0; index < packed_integers.size(); ++index) integers[static_cast<size_t>(index)] = packed_integers[index];
    for (int64_t index = 0; index < packed_floats.size(); ++index) floats[static_cast<size_t>(index)] = packed_floats[index];
    peraviz::runtime::CompiledRuntimeSceneDecodeResult decoded = peraviz::runtime::decode_compiled_runtime_scene(integers, floats);
    if (!decoded.valid) {
        peraviz::runtime::CompiledRuntimeScene rejected;
        rejected.diagnostics.push_back({"PVZ-PACKED-SCENE-DECODE", "error", decoded.diagnostic, "CompiledRuntimeScene"});
        core_.install_compiled_scene(rejected);
        return;
    }
    core_.install_compiled_scene(decoded.scene);
}

// Submits the latest snapshot for a DMX universe.
void PeravizVisualRuntime::submit_universe_frame(int universe_id, const PackedByteArray &data) {
    core_.submit_universe_frame(universe_id, data.ptr(), data.size());
}

// Consumes the latest cooked dirty visual frame as one coherent typed snapshot.
Dictionary PeravizVisualRuntime::consume_latest_visual_frame() {
    const peraviz::runtime::SectionedVisualFrame frame = core_.consume_latest_visual_frame();
    PackedInt32Array descriptors;
    descriptors.resize(static_cast<int64_t>(frame.descriptors.size()));
    for (int64_t index = 0; index < descriptors.size(); ++index) {
        descriptors.set(index, frame.descriptors[static_cast<size_t>(index)]);
    }
    PackedInt32Array integers;
    integers.resize(static_cast<int64_t>(frame.integers.size()));
    for (int64_t index = 0; index < integers.size(); ++index) {
        integers.set(index, frame.integers[static_cast<size_t>(index)]);
    }
    PackedFloat32Array floats;
    floats.resize(static_cast<int64_t>(frame.floats.size()));
    for (int64_t index = 0; index < floats.size(); ++index) {
        floats.set(index, frame.floats[static_cast<size_t>(index)]);
    }
    Dictionary out;
    out["protocol_major"] = frame.protocol_major;
    out["protocol_minor"] = frame.protocol_minor;
    out["schema_generation"] = frame.schema_generation;
    out["descriptors"] = descriptors;
    out["integers"] = integers;
    out["floats"] = floats;
    return out;
}

// Returns the installed section schema for structural registration and validation in Godot.
Dictionary PeravizVisualRuntime::get_visual_frame_schema() const {
    const peraviz::runtime::VisualFrameSchema &schema = core_.schema();
    Array sections;
    for (const peraviz::runtime::VisualSectionSchema &section : schema.sections) {
        Dictionary row;
        row["section_type"] = section.section_type;
        row["row_stride_ints"] = section.row_stride_ints;
        row["row_stride_floats"] = section.row_stride_floats;
        row["flags"] = section.flags;
        sections.push_back(row);
    }
    Dictionary out;
    out["protocol_major"] = schema.protocol_major;
    out["protocol_minor"] = schema.protocol_minor;
    out["schema_generation"] = schema.schema_generation;
    out["sections"] = sections;
    return out;
}

// Returns cumulative native runtime counters for diagnostics.
Dictionary PeravizVisualRuntime::get_stats() const {
    return stats_to_dictionary(core_.stats());
}

// Converts native visual frame stats into a Godot dictionary.
Dictionary PeravizVisualRuntime::stats_to_dictionary(const peraviz::runtime::VisualFrameStats &stats) {
    Dictionary out;
    out["packets_submitted"] = static_cast<int64_t>(stats.packets_submitted);
    out["packets_coalesced"] = static_cast<int64_t>(stats.packets_coalesced);
    out["universes_ignored"] = static_cast<int64_t>(stats.universes_ignored);
    out["universes_considered"] = static_cast<int64_t>(stats.universes_considered);
    out["fixtures_dirty"] = static_cast<int64_t>(stats.fixtures_dirty);
    out["fixtures_skipped"] = static_cast<int64_t>(stats.fixtures_skipped);
    out["changed_transform"] = static_cast<int64_t>(stats.changed_transform);
    out["changed_dimmer"] = static_cast<int64_t>(stats.changed_dimmer);
    out["changed_color"] = static_cast<int64_t>(stats.changed_color);
    out["changed_zoom"] = static_cast<int64_t>(stats.changed_zoom);
    out["color_rows"] = static_cast<int64_t>(stats.color_rows);
    out["color_targets_dirty"] = static_cast<int64_t>(stats.color_targets_dirty);
    out["color_inputs_evaluated"] = static_cast<int64_t>(stats.color_inputs_evaluated);
    out["color_targets_cooked"] = static_cast<int64_t>(stats.color_targets_cooked);
    out["changed_gobo"] = static_cast<int64_t>(stats.changed_gobo);
    out["changed_gobo_rotation"] = static_cast<int64_t>(stats.changed_gobo_rotation);
    out["gobo_topology_updates"] = static_cast<int64_t>(stats.gobo_topology_updates);
    out["gobo_parametric_updates"] = static_cast<int64_t>(stats.gobo_parametric_updates);
    out["wheel_inputs_evaluated"] = static_cast<int64_t>(stats.wheel_inputs_evaluated);
    out["wheel_targets_dirty"] = static_cast<int64_t>(stats.wheel_targets_dirty);
    out["wheel_selection_rows"] = static_cast<int64_t>(stats.wheel_selection_rows);
    out["gobo_selection_rows"] = static_cast<int64_t>(stats.gobo_selection_rows);
    out["missing_media_warnings"] = static_cast<int64_t>(stats.missing_media_warnings);
    out["deferred_multi_wheel_warnings"] = static_cast<int64_t>(stats.deferred_multi_wheel_warnings);
    return out;
}

} // namespace godot
